[dependencies]
base = "0.14.7"
new-base = "0.4.0"
json = "1.0.1"
base-x-encoder = "0.0.1"
hmac = "0.0.1"
ecdsa = "5.0.1"
sha2 = "0.1.0"

[package]
name = ""
version = "0.0.1"
description = ""
repository = "https://github.com/edjcase/"
keywords = [ ]
license = "MIT"

[dev-dependencies]
test = "2.1.1"
